# Mitoconfig Tracked File TOML Example
# Right now it is basically just my personal example file but we can fix that later

[kitty]
path = "~/.config/kitty/kitty.conf"
type = "config"


[helium]
path = "~/.config/net.imput.helium/"
type = "data"


[cpupower]
path = "/etc/default/cpupower-service.conf"
type = "config"
wrap_script = "$OPEN_IN_EDITOR && sudo systemctl restart cpupower"
# no housefire when moved to another machine, please i beg
this_machine_only = true


["hyprland, hypr"]
path = "~/.config/hypr/hyprland.lua"
type = "config"


["vesktop, discord"]
path = "~/.config/vesktop/settings/settings.json"
type = "config"


[mako]
path = "~/.config/mako/config"
type = "config"


[micro]
path = "~/.config/micro/settings.json"
type = "config"


[fastfetch]
path = "~/.config/fastfetch/config.jsonc"
type = "config"


[hyprlock]
path = "~/.config/hypr/hyprlock.conf"
type = "config"


["theme, style"]
path = "~/.config/hypr/theme.css"
type = "config"


[btop]
path = "~/.config/btop/btop.conf"
type = "config"


[kdeconnect]
path = "~/.config/kdeconnect/bba0c706_9fbf_438d_8246_458e978806da/"
type = "data"


[fish-all]
path = "~/.config/fish/"
type = "config"


[fish]
path = "~/config/fish/conf.d/my.fish"
type = "config"
wrap_script = "$OPEN_IN_EDITOR && fish"


[gtk3]
path = "~/.config/gtk-3.0/"
type = "config"


["gtk4, gtk"]
path = "~/.config/gtk-4.0/"
type = "config"


["google-chrome, chrome"]
path = "~/.config/google-chrome/"
type = "data"


["obs-studio, obs"]
path = "~/.config/obs-studio/"
type = "data"


[qbittorrent]
path = "~/.config/qBittorrent/qBittorrent.conf"
type = "config"


[vuetorrent]
path = "~/.config/vuetorrent/"
type = "config"


[firefox]
path = "~/.config/mozilla/firefox/"
type = "data"


[waybar]
path = "~/.config/waybar/config"
type = "config"


[waybar-style]
path = "~/.config/waybar/style.css"
type = "config"


["vscode, code"]
path = "~/.config/Code/"
type = "data"


[nficons]
path = "~/.config/style/nficons"
type = "config"


[vscode-extensions]
path = "~/.vscode/extensions/"
type = "config"
